import Toast from "@/components/toast/Toast";
import "./globals.css";

export const metadata = {
  title: "Powerful animale market in bangladesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toast />
      </body>

    </html>
  );
}
